---

common:
  packages:
    - automake 
    - bash-completion
    - bzip2
    - bzip2-devel
    - cabextract
    - curl
    - distribution-gpg-keys
    - dnf-plugins-core
    - fontconfig 
    - fontforge
    - gcc 
    - gcc-c++ 
    - gzip
    - intel-media-driver
    - kernel-devel
    - libffi-devel
    - make 
    - openssl-devel
    - p7zip
    - powerline-fonts
    - readline-devel
    - sqlite
    - sqlite-devel
    - unzip
    - wget
    - xorg-x11-font-utils 
    - xz
    - xz-devel
    - zip
    - zlib-devel
